gitlab:
  user_initpassword: "password1234"
  accesstoken: "gZVSzZMgzMnzkkKiwj3T" 
  gitlabDomain: "https://gitlab.choilab.com/api/v4/"

  group_member_default_expires: "2022-01-01"

  root_appId:
    python: 1
    springboot: 3
    appofapps: ''
  
jenkins:
  access_token: "1192f220a80306dbe4a07fe4d9d133dc2f"
  host: "https://choilab.com/jenkins1"
  admin_user: "admin"

  createjob:
    job_template: "job_templatev1.xml"
    