apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-tutorial-sources
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi