apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-run-
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: springboot-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/choisungwookDevops/springboot-helloworld.git
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc