persistence:
  storageSize: 8Gi  
  # storageClass: ""
  storageClass: "nfs"
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  env:
    - name: NEXUS_CONTEXT
      value: nexus
  hosts:
    - host: "helloworld.com"
      paths: 
        - path: "/nexus"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local