---
- name: configure ansible hosts
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: create hosts and configuration
      copy:
        dest: /home/vagrant/hosts
        content: |
          [master]
          192.168.0.210

          [bootstrap]
          192.168.0.211

          [agent]
          192.168.0.212