apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: jmeter-load-test
data:
  load_test: |
    #!/bin/sh
    servers=$(getent ahostsv4 jmeter-server | awk -F"  " '{ print $1 }' | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//')
    jmeter -n -t $1 -Dserver.rmi.ssl.disable=true -R $servers
