apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-server
  labels:
    jmeter_role: server
spec:
  replicas: 3
  selector:
    matchLabels:
      jmeter_role: server
  template:
    metadata:
      labels:
        jmeter_role: server
    spec:
      containers:
      - name: jmeter-server
        image: choisunguk/jmeter:server
        imagePullPolicy: Always
        ports:
        - containerPort: 1099
        - containerPort: 50000
        