apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: git-clone
  labels: 
    tekton.dev/task: git-clone
spec:
  taskRef:
    name: git-clone
  params: 
    - name: url
      value: https://github.com/choisungwookDevops/springboot-helloworld.git
    - name: revision
      value: main
  workspaces: 
    - name: output
      persistentVolumeClaim:
        claimName: maven-repo-pvc