# - name: Install lvm2
#   yum:
#     name: lvm2
#     state: latest

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: "Installing Docker latest version"
  yum:
    name: docker-ce
    state: present

- name: Create docker directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy docker daemon.json
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: "Starting and Enabling Docker service"
  service:
    name: docker
    state: started
    enabled: yes  

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"