apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
spec:
  storageClassName: "localvolumeprovisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: gitlab-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log
spec:
  storageClassName: "localvolumeprovisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: gitlab-log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
spec:
  storageClassName: "localvolumeprovisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: gitlab-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-backup
spec:
  storageClassName: "localvolumeprovisioner"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: gitlab-backup