apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 32
      targetPort: 80
  type: NodePort