apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-proxy
data:
  proxy.conf: |
    cluster redis-cluster:6379
    bind 0.0.0.0
    port 6379
    threads 8
    daemonize no  
    enable-cross-slot yes    
    auth toor
    log-level error