apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: demo-crt
spec:
  dnsNames:
    - "choilab.com"
  secretName: demo-crt
  commonName: "choilab.com"
  issuerRef:
    name: letsencrypt-cluster-issuser
    kind: ClusterIssuer