apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: demo-crt
spec:
  secretName: demo-crt
  commonName: "choilab.com"
  issuerRef:
    name: letsencrypt-cluster-issuser
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingress: nginx
        domains:
          - choilab.com