apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    run: nginx-ingress
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-ingress
  type: LoadBalancer