# reference: https://github.com/justmeandopensource/kubernetes/blob/master/yamls/nfs-provisioner/class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: nfs
volumeBindingMode: WaitForFirstConsumer