persistence:
  size: 20Gi
  existingClaim: jenkins-pvc

controller:
  image: "choisunguk/jenkins"
  tag: "v4"
  serviceType: ClusterIP
  jenkinsUriPrefix: "/jenkins"
  installPlugins: []

  ingress:
    enabled: true
    hostName: "choilab.com"
    path: "/jenkins"

docker:
  enabled: true