persistence:
  storageClass: nfs
  size: 20Gi
  existingClaim: jenkins-pvc

controller:
  image: "choisunguk/jenkins"
  tag: "v3"
  jenkinsUriPrefix: "/jenkins"
  installPlugins: []

  ingress:
    enabled: true
    hostName: "helloworld.com"
    path: "/jenkins"